name: Getdem
version: 1.0.0
description: A filter to let you filter collections by mutiple taxonomies as get params
url: https://github.com/jrc9designstudio/statamic-getdem
developer: JRC9 Design Studio & Danny Richardson
